#!/bin/bash

#getOneProductMiRFasta_forSpecies.pl takes the deepMirCut dataSet file (mir_dataset.txt), the mirbase hairpin precursor file (hairpin.fa), the mirbase gff file for human mirs (hsa.gff3), and the species prefix for human (hsa) as input.  It outputs a fasta file with precursers for mirs with only one annotated product in hsa_OneProduct.fa
perl Scripts/getOneProductMiRFasta_forSpecies.pl mir_dataset.txt hairpin.fa hsa.gff3 hsa

#compareMaxNeedleIdentity.pl takes a fasta file of human mirs with only one annotated product (hsa_OneProduct.fa), a fasta file of mirs in the training set without the buffer regions (trainSet_wSimilar_precursors.fa), and a output prefix (hsa_vs_trainSetWSimilar).  It finds the maximum identity for each mir in hsa_OneProduct.fa comapred to all mirs in trainSet_wSimilar_precursors.fa, and outputs a file listing the maximum identities in hsa_vs_trainSetWSimilar.txt
perl Scripts/compareMaxNeedleIdentity.pl hsa_OneProduct.fa trainSet_wSimilar_precursors.fa hsa_vs_trainSetWSimilar

#createOneProductTestSet.pl takes the deepMirCut dataSet file (mir_dataset.txt), and the file containing the maximum identities in hsa_vs_trainSetWSimilar.txt and outputs a test set file of microRNAs with identities less than 80 percent (test_oneProd.txt)
perl Scripts/createOneProductTestSet.pl mir_dataset.txt hsa_vs_trainSetWSimilar.txt

#addFoldsToSet.pl takes the test set (test_oneProd.txt) as input, and outputs test set file with dot-bracket folds and a bpRNA context array (test_oneProd_wFolds.txt)
perl Scripts/addFoldsToSet.pl test_oneProd.txt

#prepareNewCutsiteSets.pl takes the test set with dot-bracket frolds and bpRNA context array (test_oneProd_wFolds.txt), the hairpin file output by miRPreprocess.pl (readRegions_hairpins.txt), the products file output by miRPreprocess.pl (readRegions_products.txt), and a number indicating the minimum number of reads (in this case 5).  It adds cutsites for the unannotated products using the files generated by miRPreprocess, and then outputs two test sets based on which side the unannotated product was on (oneProd_test_3pAnnot_5pUnannot.txt, oneProd_test_5pAnnot_3pUnannot.txt)
perl Scripts/prepareNewCutsiteSets.pl test_oneProd_wFolds.txt readRegions_hairpins.txt readRegions_products.txt 5

